#!/bin/sh
#
# Configuration:
#   URL
#   REFNAME

set -e
[ "$VERBOSE" != 1 ] || set -x

DEST_DIR="$1"
CFG_FILENAME="$2"
shift
shift
PATCHES="$@"

. "$CFG_FILENAME"

CLONE_DIR="build/git/$(echo "$URL" | sed 's|//|/|')"

if [ -z "$URL" ]; then
	echo "ERROR: missing required configuration: URL" >&2
	exit 1
elif [ -z "$REFNAME" ]; then
	echo "ERROR: missing required configuration: REFNAME" >&2
	exit 1
fi

# Ensure git has a valid committer identity for patching
if ! git var GIT_COMMITTER_IDENT >/dev/null 2>&1; then
    echo "Git committer identity not configured, setting defaults"

    git config --global user.name  "${GIT_USER_NAME:-Build System}"
    git config --global user.email "${GIT_USER_EMAIL:-build@example.invalid}"
fi

if [ "$MAKROCOSM_GIT_CLONE_SHALLOW" = 1 ]; then
	# In some environments (e.g. CI build pipeline) we don't care about shared
	# git repo with the entire history. Shallow clone the repo.
	echo "Shallow cloning from remote $URL into target $DEST_DIR" >&2
	rm -rf "$DEST_DIR"
	mkdir -p "$DEST_DIR"
	git -C "$DEST_DIR" init && git -C "$DEST_DIR" remote add origin "$URL" && git -C "$DEST_DIR" fetch --depth 1 origin "$REFNAME" && git -C "$DEST_DIR" checkout FETCH_HEAD
	for patch in $PATCHES; do
		echo "Applying patch $patch" >&2
		git -C "$DEST_DIR" am "$(pwd)/$patch" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$patch"
	done

	echo "git $URL $REFNAME $PATCHES" > "$DEST_DIR.src"
	exit 0
fi

if [ ! -d "$CLONE_DIR" ]; then
	echo "Cloning from remote $URL into shared $CLONE_DIR" >&2
	git clone "$URL" "$CLONE_DIR"
fi
	
if [ -z "$(git -C "$CLONE_DIR" rev-list -n 1 "$REFNAME" --)" ]; then
	echo "$REFNAME is not available in local shared repository. Fetching updates..." >&2
	git -C "$CLONE_DIR" fetch
fi

echo "Cloning from local shared repository into target $DEST_DIR" >&2
rm -rf "$DEST_DIR"
git clone "$CLONE_DIR" "$DEST_DIR"
git -C "$DEST_DIR" checkout "$REFNAME" --

for fn in $PATCHES; do
	case "$fn" in
		*.patch)
			echo "Applying patch: $fn" >&2
			git -C "$DEST_DIR" am "$(pwd)/$fn" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$fn"
			;;
		*.series)
			echo "Applying patch series: $fn" >&2
			while IFS= read -r patch; do
				case "$patch" in
					\#*)
						echo "Skipping patch in series: $patch" >&2
						;;
					*.patch)
						echo "Applying patch in series: $patch" >&2
						git -C "$DEST_DIR" am "$(pwd)/$patch" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$patch"
						;;
					'') ;; # Skip blank lines
					*)
						echo "ERROR: Not a patch: $patch"
						exit 1
						;;
				esac
			done < "$fn"
			;;
		*)
			echo "ERROR: Not a patch or patch series: $fn"
			exit 1
			;;
	esac
done

echo "git $URL $REFNAME $PATCHES" > "$DEST_DIR.src"
