#!/bin/sh
#
# Pad a file out to a fixed number of bytes.
#
# usage: pad CFG_FILENAME SRC_FILENAME DEST_FILENAME
#
# Configuration:
#   SIZE

set -e
[ "$VERBOSE" != 1 ] || set -x

CFG_FILENAME="$1"
SRC_FILENAME="$2"
DEST_FILENAME="$3"

. "$CFG_FILENAME"

calc_bytes() {
  units -t -o '%.100g' "$1" B
}

canonicalize_size() {
  # Append "iB" if doesn't end with a "B" e.g. "MiB" or "MB"
  if [ "${1%b}" = "$1" -a "${1%B}" = "$1" ]; then
    echo "${1}iB"
  else
    echo "$1"
  fi
}

SIZE="$(canonicalize_size "$SIZE")"
SIZE="$(calc_bytes "$SIZE")"
SRC_SIZE="$(stat -c '%s' "$SRC_FILENAME")"

if [ "$SRC_SIZE" -gt "$SIZE" ]; then
  echo "ERROR: Cannot grow file. Input file $SRC_FILENAME ($SRC_SIZE bytes) exceeds target size $SIZE bytes."
  exit 1
fi

cp -f "$SRC_FILENAME" "$DEST_FILENAME"
truncate -s "$SIZE" "$DEST_FILENAME"
